### PR TITLE
ci: add Python 3.12 alpha to tests

### PR DESCRIPTION
**Pull request by shenanigansd**

### CODE REVIEW

**Comment by SomeHybrid** [comment]
ok  guys merge this rn

**Comment by shenanigansd** [comment]
> ok guys merge this rn

Just need an approval
@Robin5605 get in here

**Review by dawnofmidnight — CHANGES_REQUESTED** [review]
not enough 🚀 emojis in the comments

**Comment by SomeHybrid** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀

**Review by ionite34 — APPROVED** [review]

**Review by Robin5605 — APPROVED** [review]

**Pull request merged**
