### PR TITLE
Test the uwuification

### LINKED ISSUE #10: Add tests for uwuification
Add tests for all uwuification methods. The strengths can be set higher than the limit to guarantee the output.

### PR DESCRIPTION
**Pull request by shenanigansd**
Fixes #10

### CODE REVIEW

**Comment by SomeHybrid** [comment]
suggestion: add pytest to install-dev

**Comment by shenanigansd** [comment]
> suggestion: add pytest to install-dev

It already is, it's provided by the `dev` extra.

**Review by Preocts — COMMENTED** [review]
lgtm 🚀

**Comment by SomeHybrid** [comment]
hm yes very good 🚀 merge now robin

**Review by Robin5605 — APPROVED** [review]
i am satisfied

**Pull request merged**
