### PR TITLE
Uwuification cleanup

### LINKED ISSUE #23: Uwuification unnecessarily repetitive
A lot of the logic in the `uwuification` module is very repetitive.

### PR DESCRIPTION
**Pull request by shenanigansd**
Close #23

### CODE REVIEW

**Comment by SomeHybrid** [comment]
rip linter

**Comment by SomeHybrid** [comment]
make `random_dice` `_random_dice`

**Comment by SomeHybrid** [comment]
add re.compile to the regexes outside of the function?

**Comment by shenanigansd** [comment]
How does this help it?

**Pull request closed without merging**
