### PR TITLE
jsification

### PR DESCRIPTION
**Pull request by SomeHybrid**
Created JS version (kinda scuffed but it works)

### CODE REVIEW

**Comment by SomeHybrid** [comment]
> Not sure how good / useful an idea it is to include a JavaScript client in a Python package, with Python tooling

its for #25

**Comment by shenanigansd** [comment]
I'm with @Robin5605, I'd be happy to make a JS repo, but I don't want to try and keep multiple implementations in the same repo. Shall we proceed with the JS repo?

**Comment by SomeHybrid** [comment]
sure ig

**Comment by shenanigansd** [comment]
Very well, please continue the jsification over there --> https://github.com/letsbuilda/imsosorrybutinjs

**Comment by shenanigansd** [comment]
Handled in https://github.com/letsbuilda/imsosorrybutinjs/pull/1

**Pull request closed without merging**
